# Pandas and Matplotlib Homework

In [1]:
#load the libraries using the normal convention
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
##prevent plotting errors
%matplotlib inline

In [34]:
#Load our excel files of interest into pandas
NHL_Goalies = pd.read_excel('NHLGoalies2016_2017.xls',na_values='',sheet_name=0) 
GAA_ = pd.read_excel('NHLGoalies2016_2017.xls',na_values='',sheet_name='5vs5')
NHL_Goalies
GAA_

,First Name,Last Name,Team,TOI,GAA,GSAA,SV%,TrueSV%,ExpSV%,xGSAA,...,SF,xGF,GF,RebF,RushF,Supp,ZS%,OZS,DZS,NZS
0,Allen,Jake,STL,2692.83,2.139014,1.718026,0.924588,0.959630,0.923551,1.32,...,1307,104.22,113,78,97,2.517797,0.476449,789,867,919
1,Alves,Jorge,CAR,0.13,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,...,0,0.00,0,0,0,0.000000,1.000000,1,0,0
2,Andersen,Frederik,TOR,2997.20,2.342186,6.510058,0.927284,0.961078,0.916774,16.91,...,1531,140.48,139,74,181,2.782597,0.478216,922,1006,1100
3,Anderson,Craig,OTT,1908.44,1.854918,16.994380,0.940404,0.969255,0.922778,17.45,...,986,78.14,74,95,119,2.326508,0.525227,635,574,647
4,Bachman,Richard,VAN,244.84,2.695638,-0.330082,0.920863,0.958015,0.907626,1.84,...,107,8.77,8,4,18,1.960464,0.476821,72,79,80
5,Bernier,Jonathan,ANA,1535.89,2.226722,-0.426406,0.922659,0.962525,0.916771,4.34,...,760,70.45,67,51,80,2.617375,0.459653,450,529,529
6,Berra,Reto,FLA,248.43,3.381234,-5.095608,0.879310,0.936364,0.901034,-2.52,...,129,9.50,9,10,14,2.173651,0.492754,68,70,97
7,Berube,Jean-Francois,NYI,444.72,3.103076,-5.037692,0.901709,0.942211,0.925726,-5.62,...,241,18.16,19,12,21,2.563411,0.444079,135,169,161
8,Bibeau,Antoine,TOR,81.36,1.474926,0.993718,0.948718,0.975000,0.924615,0.94,...,64,4.74,2,0,4,1.474926,0.516667,31,29,22
9,Bishop,Ben,"TBL, LAK",1700.08,2.152840,1.023696,0.924505,0.959115,0.919059,4.40,...,888,73.53,64,71,86,2.258717,0.525653,584,527,639
10,Bobrovsky,Sergei,CBJ,2947.94,1.811434,22.458424,0.938705,0.967447,0.911660,39.27,...,1512,128.39,118,96,122,2.401677,0.493795,955,979,1003
11,Brossoit,Laurent,EDM,261.80,2.062643,0.825536,0.929688,0.963710,0.910625,2.44,...,141,11.61,16,7,14,3.666921,0.559524,94,74,109
12,Budaj,Peter,"LAK, TBL",2612.57,1.906169,2.282582,0.925293,0.961892,0.914464,12.03,...,1342,109.74,93,107,134,2.135828,0.562232,917,714,897
13,Campbell,Jack,LAK,15.98,0.000000,0.307048,1.000000,1.000000,0.962500,0.15,...,9,0.62,0,0,1,0.000000,0.666667,4,2,5
14,Comrie,Eric,WPG,53.12,4.518072,-1.159806,0.891892,0.937500,0.890811,0.04,...,27,2.45,3,0,2,3.388554,0.411765,14,20,16
15,Condon,Mike,"PIT, OTT",1787.11,2.283016,-2.905824,0.919811,0.960807,0.914222,4.74,...,857,69.43,60,73,94,2.014426,0.494392,573,586,627
16,Copley,Pheonix,STL,46.89,2.559181,-0.464760,0.900000,0.945946,0.907000,-0.14,...,27,2.26,2,2,1,2.559181,0.592593,16,11,19
17,Coreau,Jared,DET,561.92,2.882973,-5.660164,0.902878,0.948864,0.914353,-3.19,...,279,24.19,29,13,28,3.096526,0.487106,170,179,225
18,Crawford,Corey,CHI,2608.24,2.139374,8.939936,0.929970,0.961475,0.919187,14.32,...,1348,105.13,103,50,112,2.369414,0.512674,809,769,899
19,Darling,Scott,CHI,1403.79,1.923365,10.191878,0.937413,0.965358,0.916120,15.31,...,668,56.51,62,49,60,2.649969,0.527881,426,381,487
20,Dell,Aaron,SJS,942.67,1.463927,11.466138,0.948775,0.974918,0.913185,15.98,...,408,36.35,33,33,41,2.100417,0.507853,291,282,308
21,Domingue,Louis,ARI,1260.90,2.569593,-0.650410,0.922302,0.959060,0.913453,6.15,...,577,44.05,49,51,53,2.331668,0.449819,372,455,440
22,Driedger,Chris,OTT,32.42,7.402838,-2.925332,0.714286,0.888889,0.904286,-2.66,...,13,0.93,0,2,0,0.000000,0.586207,17,12,9
23,Dubnyk,Devan,MIN,3025.38,2.022886,10.916902,0.930659,0.963467,0.931815,-1.70,...,1516,124.26,134,118,130,2.657517,0.501867,941,934,1041
24,Elliott,Brian,CGY,2195.05,2.186738,-2.086570,0.921182,0.957627,0.917025,4.22,...,1078,86.77,84,63,125,2.296075,0.478834,690,751,791
25,Enroth,Jhonas,TOR,211.21,4.829317,-8.095608,0.853448,0.912371,0.914655,-7.10,...,107,9.28,4,6,10,1.136310,0.514493,71,67,71
26,Fleury,Marc-Andre,PIT,1644.77,2.735945,-5.683914,0.916944,0.953271,0.915271,1.51,...,923,80.70,70,79,72,2.553549,0.554702,578,464,627
27,Forsberg,Anton,CBJ,47.10,3.821656,-1.080950,0.880000,0.931818,0.924800,-1.12,...,24,3.17,3,0,3,3.821656,0.500000,19,19,16
28,Gibson,John,ANA,2269.48,1.877082,12.593818,0.934803,0.964990,0.917062,19.32,...,1105,98.89,78,82,117,2.062146,0.500349,716,715,720
29,Gillies,Jon,CGY,50.17,1.195934,0.919050,0.960000,0.980392,0.867600,2.31,...,19,1.78,3,1,4,3.587801,0.343750,11,21,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,Mrazek,Petr,DET,2200.09,2.536260,-7.333608,0.916667,0.953219,0.916013,0.73,...,1026,85.96,82,47,83,2.236272,0.523628,687,625,754
66,Murray,Matt,PIT,2174.15,2.014580,12.436106,0.934412,0.965679,0.912794,24.06,...,1206,109.64,114,105,89,3.146057,0.510519,728,698,814
67,Nedeljkovic,Alex,CAR,19.50,0.000000,1.228192,1.000000,1.000000,0.913125,1.39,...,10,0.86,0,2,0,0.000000,0.666667,10,5,8
68,Neuvirth,Michal,PHI,1080.96,2.553286,-9.921860,0.902128,0.953109,0.917043,-7.01,...,571,44.15,27,41,56,1.498668,0.542614,382,322,394
69,Niemi,Antti,DAL,1352.74,2.705620,-9.646222,0.908819,0.954478,0.913857,-3.37,...,678,59.52,49,52,66,2.173367,0.471251,418,469,510
70,Nilsson,Anders,BUF,1194.77,2.259849,5.432634,0.931507,0.962871,0.913957,11.53,...,570,44.13,32,31,66,1.607004,0.471354,362,406,402
71,Pavelec,Ondrej,WPG,367.04,2.778989,-2.722268,0.908602,0.947531,0.914516,-1.10,...,179,15.89,18,9,25,2.942459,0.500000,108,108,120
72,Peters,Justin,ARI,117.77,2.037870,0.912768,0.937500,0.960784,0.913438,1.54,...,58,4.79,4,6,4,2.037870,0.500000,35,35,36
73,Pickard,Calvin,COL,2223.35,2.779589,-12.113792,0.913007,0.950600,0.924907,-14.09,...,1048,77.92,65,55,67,1.754110,0.475342,694,766,750
74,Price,Carey,MTL,2944.40,1.833990,17.773848,0.935897,0.966443,0.918711,24.13,...,1538,129.80,117,134,229,2.384187,0.473908,890,988,1020
75,Quick,Jonathan,LAK,742.14,2.021182,1.252604,0.926901,0.962349,0.904795,7.56,...,372,31.91,22,38,42,1.778640,0.544747,280,234,245
76,Raanta,Antti,NYR,1265.13,1.991890,6.206536,0.933121,0.964854,0.919506,8.55,...,654,54.61,48,28,55,2.276446,0.466752,365,417,433
77,Rask,Tuukka,BOS,2850.93,2.104576,-3.433404,0.920509,0.958915,0.923029,-3.17,...,1564,117.63,109,86,112,2.293988,0.527568,976,874,1052
78,Reimer,James,FLA,1803.34,2.195925,9.533808,0.932927,0.959756,0.922581,10.18,...,956,70.74,62,55,85,2.062839,0.502591,582,576,605
79,Rinne,Pekka,NSH,2789.09,2.086702,8.240702,0.929249,0.961781,0.925208,5.54,...,1448,112.88,112,86,140,2.409388,0.512582,937,891,1001
80,Rittich,David,CGY,18.65,0.000000,0.460572,1.000000,1.000000,0.953333,0.28,...,6,0.81,0,3,0,0.000000,0.500000,5,5,5
81,Saros,Juuse,NSH,950.10,2.273445,1.843666,0.926978,0.961415,0.914016,6.39,...,496,40.23,43,40,50,2.715504,0.459200,287,338,329
82,Schneider,Cory,NJD,2686.76,2.367163,-1.296632,0.922287,0.955312,0.921268,1.39,...,1223,99.44,75,55,76,1.674880,0.459362,763,898,919
83,Smith,Jeremy,COL,465.69,3.092186,-5.346834,0.901235,0.941032,0.919835,-4.52,...,216,16.69,17,10,22,2.190298,0.523132,147,134,140
84,Smith,Mike,ARI,2534.38,2.580513,3.072520,0.925342,0.960132,0.911521,20.18,...,1174,95.47,79,105,90,1.870280,0.427150,730,979,883
85,Stalock,Alex,MIN,99.27,1.813237,0.224004,0.928571,0.961039,0.925476,0.13,...,51,3.20,4,2,8,2.417649,0.416667,30,42,44
86,Stolarz,Anthony,PHI,282.43,1.487094,3.823442,0.950355,0.972000,0.916028,4.84,...,145,13.10,9,9,14,1.911978,0.521212,86,79,100
87,Subban,Malcolm,BOS,26.18,4.583652,-0.925332,0.857143,0.904762,0.910000,-0.74,...,13,1.39,0,0,1,0.000000,0.800000,12,3,8
88,Talbot,Cam,EDM,3417.26,2.106951,8.729874,0.928444,0.962512,0.909511,31.75,...,1725,150.31,141,109,173,2.475668,0.502134,1059,1050,1172
89,Tokarski,Dustin,ANA,6.97,0.000000,0.230286,1.000000,1.000000,0.943333,0.17,...,4,0.37,0,0,0,0.000000,0.333333,1,2,1
90,Ullmark,Linus,BUF,50.13,2.393776,0.149336,0.928571,0.953488,0.926071,0.07,...,24,1.25,2,0,5,2.393776,0.382353,13,21,12
91,Varlamov,Semyon,COL,1033.25,3.251875,-12.245660,0.901754,0.945098,0.924877,-13.18,...,472,33.21,29,20,41,1.684007,0.487218,324,341,376
92,Vasilevskiy,Andrei,TBL,2209.61,2.335254,0.587536,0.923759,0.956500,0.927961,-4.74,...,1081,85.99,75,87,91,2.036558,0.489650,686,715,761
93,Ward,Cam,CAR,2939.53,2.571840,-15.078910,0.912803,0.952255,0.913170,-0.53,...,1425,133.43,108,130,167,2.204434,0.548611,948,780,963
94,Zatkoff,Jeff,LAK,453.09,3.045752,-8.722268,0.876344,0.933333,0.922043,-8.50,...,226,19.97,13,23,24,1.721512,0.570033,175,132,141

#Appendix:
 1. DF = Pandas DataFrame
 2. NHL_Goalies DF = NHL_Goalies 
 3. GAA_ DF = GAA_

### Q1A) Create a new DF (*called NHL_Ones*) by:
#### Filtering the correct DF for Goalies that played 1 game <font color='red'> (GP = Games played)</font>

Notes: How would you find the 'GP' column in these files? Review from Pandas Lecture

In [35]:
#Answer 1A:

NHL_Ones= NHL_Goalies.loc[NHL_Goalies.GP==1].copy()
NHL_Ones

,Last Name,First Name,Team,DOB,Birth City,S/P,Cntry,Nat,Ht,Wt,...,Cap Hit,Pace,1st,2nd,3rd,Star,GPS,Ginj,Injuries,CHIP
1,Alves,Jorge,CAR,1979-01-30,Boston,MA,USA,USA,69,185,...,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,NaN,NaN,
13,Campbell,Jack,LAK,1992-01-09,Port Huron,MI,USA,USA,74,197,...,NaN,96.000000,NaN,NaN,NaN,NaN,0.1,NaN,NaN,
14,Comrie,Eric,WPG,1995-07-06,Edmonton,AB,CAN,CAN,73,175,...,645000.0,124.451939,NaN,NaN,NaN,NaN,0.2,NaN,NaN,
16,Copley,Pheonix,STL,1992-01-18,North Pole,AK,USA,USA,76,196,...,708750.0,104.864253,NaN,NaN,NaN,NaN,-0.1,NaN,NaN,
22,Driedger,Chris,OTT,1994-05-18,Winnipeg,MB,CAN,CAN,76,205,...,755000.0,123.000000,NaN,NaN,NaN,NaN,-0.2,NaN,NaN,
27,Forsberg,Anton,CBJ,1992-11-27,Härnösand,NaN,SWE,SWE,75,192,...,650000.0,110.611664,NaN,NaN,NaN,NaN,0.0,NaN,NaN,
29,Gillies,Jon,CGY,1994-01-22,Concord,NH,USA,USA,78,223,...,925000.0,109.000000,1.0,0.0,0.0,1.0,0.3,NaN,NaN,
32,Gudlevskis,Kristers,TBL,1992-07-31,Aizkraukle,NaN,LVA,LVA,75,223,...,NaN,125.764192,NaN,NaN,NaN,NaN,0.0,NaN,NaN,
42,Jarry,Tristan,PIT,1995-04-29,Surrey,BC,CAN,CAN,74,194,...,630833.0,107.234043,NaN,NaN,NaN,NaN,0.0,NaN,NaN,
50,Langhamer,Marek,ARI,1994-07-22,Moravska Trebova,NaN,CZE,CZE,74,193,...,648333.0,88.936627,NaN,NaN,NaN,NaN,0.0,NaN,NaN,
67,Nedeljkovic,Alex,CAR,1996-01-07,Parma,OH,USA,USA,72,198,...,NaN,102.170284,NaN,NaN,NaN,NaN,0.3,NaN,NaN,
80,Rittich,David,CGY,1992-08-19,Jihlava,NaN,CZE,CZE,75,202,...,NaN,108.000000,NaN,NaN,NaN,NaN,0.0,NaN,NaN,
87,Subban,Malcolm,BOS,1993-12-21,Toronto,ON,CAN,CAN,74,200,...,863333.0,107.843137,NaN,NaN,NaN,NaN,-0.1,NaN,NaN,
89,Tokarski,Dustin,ANA,1989-09-16,Watson,SK,CAN,CAN,72,205,...,NaN,91.993186,NaN,NaN,NaN,NaN,0.1,NaN,NaN,
90,Ullmark,Linus,BUF,1993-07-31,Lugnvik,NaN,SWE,SWE,76,221,...,775833.0,100.113507,NaN,NaN,NaN,NaN,0.2,NaN,NaN,

 ## Q1B) 
 #### A. Find the value of the minimum Salary for the entire dataset 
 #### B. Replace the missing values from the NHL_Ones DF with this
 #### C. Create a new DF after replacement by **adding** a column called  "Adjusted_Salary"
 #### D. I would like to only see the old "Salary" column and the "Adjusted Salary" column from the new Dataframe

#### Notes:
1. Note where the minimum Salary value is coming & where you are going to assign it to
2. Review notes from pandas **replacement**
3. Look up Numpy definition for null
4. Look up Pandas **Series** Naming 
5. Review concat function in Pandas
6. Review how to slice columns

In [4]:
#Answer 1B:
Min_Salary= np.min(NHL_Ones['Salary'])
Min_Salary
## We can use the numpy to specify
#df2 = df2.replace('NaN',np.nan)
#print(df2.isnull())
dataframe_replace = NHL_Ones.replace(np.nan, Min_Salary)
dataframe_replace['Salary']
df_adjusted= pd.DataFrame({'Salary':NHL_Ones['Salary'],'Adjusted Salary':dataframe_replace['Salary']})
df_adjusted

      Salary  Adjusted Salary
1        NaN         575000.0
13       NaN         575000.0
14  575000.0         575000.0
16  708750.0         708750.0
22  780000.0         780000.0
27  650000.0         650000.0
29  925000.0         925000.0
32       NaN         575000.0
42  575000.0         575000.0
50  673334.0         673334.0
67       NaN         575000.0
80       NaN         575000.0
87  832500.0         832500.0
89       NaN         575000.0
90  892500.0         892500.0

### Q2) A. Subset the NHL goalies data to include Goalies that played in more than 25 games AND have a GAA lower than 3.00 and store the New DF as 'workhorse'

Notes: 
1. Review notes from Pandas Lecture on creating masks
2. Internet search for Multiple Boolean indexing on multiple columns in a Pandas DataFrame

In [43]:
#Answer 2:
workhorse= pd.DataFrame(NHL_Ones.loc[NHL_Ones.GP>=25] and NHL_Ones.iloc[NHL_Ones.GAA <= 3])
workhorse

ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

### Q3. Create 2 python functions that: 
<br> </br>
#### A. Creates/*Returns* a new DataFrame that displays the number of missing values in every column. 
#### This new DataFrame has one new column named "Missing" with the sum of the missing values from the columns

### Notes 
***Function takes one argument: An input DataFrame***
<br> </br>
<br> </br>
** One Proposed method:**
1. Create a pandas series object from the sum of the nulls in every column (review class notes)
2. Convert the series object to a DataFrame and pass the list of column names from the input DataFrame as the index. (read Pandas Help online)
3. During the conversion of the series object to a DataFrame pass a columns argument to create a name for the new Output DataFrame's Column.

### Expected Output:
<img src='Missing_cols_expectedoutput.png'>

In [ ]:
# Answer 3A: CODE HERE; Please comment each part

#### B. Creates a new *column* called 'missing_values' in the input DF that sums the missing values in each row.

### Notes: 
***Function takes one argument: An input DataFrame***
<br> </br>
<br> </br>
Review the Column creation method in lecture and the axis arguments needed

### Expected Output:
<img src= 'missingrows_expectedoutput.png'>

In [ ]:
#Answer 3B here; Please comment each part

### Q4) Matplotlib Question Plot in one figure and 2 side by side plots:
<br> </br>
#### A. Plot the histogram of the all the GAA of the NHL_Goalies DF  AND the goalies that played in more than 25 games with a GAA < 3.00, 
#### B. Label the Titles of the plots differently (*ie EntireSet + Subset*)
#### C. Change the color of one of the plots from the default

# Notes

1. convert your column of interest into a NumPY array (look up online for usage)
2. Review: https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.hist.html

In [ ]:
#Answer 4 here: pleae comment

### Q5) GroupBy Question
##### 1. Subset the NHL_Goalies DataFrame where Injuries is not known <font color='red'>(Injuries=NaN)</font>; 
##### 2. Use a Merge with the GAA_  DF to produce a NEW DF (*called mergedDF*) 
###### *** USE A JOIN THAT PRESERVES ORDER AND USES THE INTERSECTION OF KEYS***
###### *** USE BOTH THE LEFT AND RIGHT INDEXES AS JOIN KEYS***
##### 3. From the mergedDF keep FirstName/LastName/Team/Cntry/ SV% /GA/GAA/ TOI (note one copy for any duplicate column)
##### 4. GroupBy country on mergedDF and aggregate The Means, Mins, and Maximum of the kept columns
#### 5. Create a dataframe of the <font color='red'>TOI </font>groupby object and write it to a comma seperated value file called ('TOI_2017.csv')

## Notes:

1. Review how to create selection criteria and how aggs/joins work from lecture notes;
2. https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.to_csv.html
3. https://stackoverflow.com/questions/14734533/how-to-access-pandas-groupby-dataframe-by-key
4. https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.get.html

In [ ]:
#Answer 5 here: please comments

# Q6) Write a function(s)  
## that subsets a dataframe by removing rows that are WITHIN the InterQuartile Region of a specified column
<br> </br>
### The function takes as input 
##### A: Pandas_Dataframe (For example use NHL_GoaliesDF)
##### B. Column name
### Add a condition that returns an error if the Column Name chosen is not:
##### A. Numeric Dtype
##### B. Does not exist in the Numeric Columns
### The output is a DataFrame that removes rows outside of the specified columns IQR
<br> </br>
<font color='red'>**You can use smaller helper functions **<font>
<br> </br>
See --> <href>=https://en.wikipedia.org/wiki/Interquartile_range</href>
#hint: There are several pandas subfunctions that can be useful

In [ ]:
#Answer Question 6 here

***For any questions regarding this assignment please email SAMSON: <br> </br><font color='green'>sjacob210@gmail.com ***</font>